### ISSUE TITLE
A new CKAN instance setup using latest updates

### ISSUE THREAD

**Issue by anuveyatsu** [datopian/birmingham-city-observatory#1]
## Acceptance

- [x] I have a brand new CKAN instance running

## Tasks

- [x] Setup a new instance with clean DB and using latest CKAN version running on Python 3
- [x] Setup Datopian's internal domain for easy access - https://birmingham-city-observatory.datopian.com/
- [x] Install Datopian's enterprise theme

**Comment by anuveyatsu** [comment]
FIXED, the new instance is served from here: https://birmingham-city-observatory.datopian.com/

Note that the domain will change to Birmingham City's one prior to production release in Sep/Oct.
