### ISSUE TITLE
Implement contact

### ISSUE THREAD

**Issue by demenech** [datopian/birmingham-city-observatory#11]
Currently, the contact page only displays a contact form, not actually sending any message.

## Acceptance Criteria
- [x] I can send contact messages through the contact form

## Tasks
- [x] Find out how the contacts are gonna be received (e.g. an email is gonna be sent to the client)
- [x] Make the form be sent
- [x] Make the contact us page picture the same as the rest of the pages
- [x] Feedback button - remove automatic subject when when directed to the contact page from the feedback button

**Comment by juanbrits** [comment]
@lucasmbispo form to be sent to: cityobservatory@birmingham.gov.uk

**Comment by juanbrits** [comment]
@lucasmbispo I've added another task to the issue. this image on Contact Page needs to be replaced with the pink that is present on other tabs:

![image](https://user-images.githubusercontent.com/103997912/191700573-b3548db9-0653-4573-a345-650ef29fcf6d.png)

![image](https://user-images.githubusercontent.com/103997912/191700660-065150ad-a4a3-4df5-9085-fd0f9c4dbd5d.png)

**Comment by juanbrits** [comment]
We require the following from the client:
We need 2 emails
1 that sends the emails
We need an SMTP server, email and password details
1 that receives the emails
This is to whom the contact us form should be sent

Requested from client via email.

**Comment by juanbrits** [comment]
@demenech a new task has been added. Please review and advise if all is in order?

**Comment by demenech** [comment]
@juanbrits done.

**Comment by juanbrits** [comment]
Awaiting SMTP details from client

**Comment by juanbrits** [comment]
Client confirmed that the test contact form was received. This is live and sending to: [cityobservatory@birmingham.gov.uk](mailto:cityobservatory@birmingham.gov.uk)
