### ISSUE TITLE
Standardize titles and logos

### ISSUE THREAD

**Issue by demenech** [datopian/birmingham-city-observatory#13]
## Acceptance Criteria
- [ ] All logos are up to date
- [ ] All titles are up to date

## Tasks
- [x] Find out the The City Observatory logo
- [x] Update the navbar to use this logo
- [x] Update the favicon to use this logo
- [x] Update the footer to use this logo
- [x] Find out the title the client wants to use for the project
- [x] Update the title everywhere (e.g. replace Open Data Birmingham City Observatory with the correct title)

**Comment by juanbrits** [comment]
@demenech please advise on this issue?
