### ISSUE TITLE
Standardize terminology

### ISSUE THREAD

**Issue by demenech** [datopian/birmingham-city-observatory#14]
## Acceptance Criteria
- [x] Names are updated

## Tasks
- [x] Find out how the client wants to name:
    - [x] Organizations
    - [x] Groups
    - [x] Posts
- [x] Update the names site-wide

**Comment by juanbrits** [comment]
@demenech from my view this is resolved. 

- Organization has changed to Organisation
- Collections have changed to Themes
- Posts is News
