### ISSUE TITLE
Static pages

### ISSUE THREAD

**Issue by demenech** [datopian/birmingham-city-observatory#15]
## Acceptance Criteria
- [x] Static pages are updated

## Tasks
- [x] Discuss with the client if we should keep all the static pages
- [x] For the pages that we are going to keep, discuss the content:
    - [x] Cookies
    - [x] Privacy
    - [x] Terms and Conditions
    - [x] About

**Comment by juanbrits** [comment]
@demenech the client has requested a change on the about page. Please see below:

Left align text so that the right side is open for images
Column like fashion

**Comment by demenech** [comment]
@juanbrits waiting for the images.

**Comment by juanbrits** [comment]
@demenech please note that we need to correct this character on the About Page:

![image](https://user-images.githubusercontent.com/103997912/195544952-4e630746-4c90-4f4e-b80a-b3f7310c5bb8.png)

**Comment by demenech** [comment]
hi, @juanbrits 
I'm sorry, I missed this message. I will fix this tomorrow as early as possible.

**Comment by juanbrits** [comment]
@demenech the client has requested a last minute change to the text on the about page. Please see below:

About:  

The City Observatory’s mission is to unlock data in Birmingham. 
With a city that has a population of over 1.1 million people across 69 wards open data is vital to opportunities for growth, economic development, tackling inequalities and levelling up. 
We want to ensure decisions that are made to improve outcomes for citizens are evidenced by accurate, current data and insight. This site is our first step to becoming a more open and transparent city. We believe the approach can generate many benefits including: 

•	Giving you direct access to data to build your own opinions
•	Allows datasets to be combined to create new insights
•	Enabling the sharing of data
•	Allowing application developers to use real data 
•	Enabling collaboration across organisations 

We aim to collate and publish a range of datasets that you can download and reuse as you see fit.
However, releasing raw data alone, though useful, is often only part of the solution.  That’s why our team of curious minds are committed to providing insights and evidence into key datasets we publish. Our ambition is to create a widely understood ‘single version of the truth’ about Birmingham.  We hope our work will: 
•	Stimulate thinking
•	Encourage collaboration
•	Enrich delivery 
•	And drive positive change for citizens
If you want to get involved, collaborate with us, share your ideas and feedback, email us at cityobservatory@birmingham.gov.uk

**Comment by juanbrits** [comment]
@demenech the client is happy with the about page. As such will be closing off this issue.
