### ISSUE TITLE
Homepage groups carousel

### ISSUE THREAD

**Issue by demenech** [datopian/birmingham-city-observatory#17]
## Acceptance Criteria
- [x] I can see the group title under each group icon

## Tasks
- [x] Group Icons on the home page should have a title for each
- [x] On home page all groups should be featured
- [x] Change icons row into a carousel
- [x] to make a list of groups with no icon so that we can show all icons
- [x] Make sure icons have transparent background
- [ ] ~Delete groups that are not needed~ (didn't do it because there are datasets associated with the groups)

**Comment by demenech** [comment]
## Groups that do not have an image:
Economy 
Environment 
Leisure and culture 
Locations 
Tourism
Travel and transport
Your local area
Mycare

**Comment by juanbrits** [comment]
Hi @demenech I see 11 groups on the old data portal? Why have we only included 9?

**Comment by demenech** [comment]
Hi, @juanbrits 
I have hidden the groups that do not have an image for now. I can revert this anytime.

**Comment by juanbrits** [comment]
@demenech please confirm which groups do not have an icon?

**Comment by demenech** [comment]
@juanbrits the groups are listed on a comment above

**Comment by demenech** [comment]
@juanbrits I changed the icons, but it seems like it's not updating in the front end. I'm going to recheck that tomorrow. (the back end displays the updated icons). Also, I didn't delete the groups because there are datasets associated with them.

**Comment by juanbrits** [comment]
Closing issue as this has been QA'd and resolved.
