### ISSUE TITLE
Migrate database from old instance

### ISSUE THREAD

**Issue by anuveyatsu** [datopian/birmingham-city-observatory#2]
From https://data.birmingham.gov.uk/ to https://birmingham-city-observatory.datopian.com/

## Acceptance

- [x] I have all datasets (metadata, data files and datastore tables), orgs, groups and other objects in the new instance.

## Tasks

- [x] Perform db migration
  * [x] Clean the `birmingham-city-prod` current db
  * [x] Take a psql dump of `birmingham-prod` db
    * [x] Refactor it to use the user of `birmingham-city-prod` db
  * [x] Create a new db for the birmingham-city-prod with the right permissions 
  * [x] Apply the new SQL dump to the `birmingham-city-prod` db
  * [x] Do the same for the datastore db
  * [x] Reindex solr
- [x] Test
- [x] Report

**Comment by joyisi** [comment]
@anuveyatsu I am going to test the data migration locally to be sure it works fine, before implementing it on the portal.

I would also require access to the portal, as i do not have at the moment.

**Comment by anuveyatsu** [comment]
@joyisi can we start with some preliminary analysis around:

- current size of blob storage
- size of CKAN db
- size of DataStore db

We can then decide what would be the best strategy for migration.

For access, I think you need to ping the SRE team.

**Comment by joyisi** [comment]
@anuveyatsu the ckan db was migrated to the new instance. Datastore hasn't been done yet. That should be done today. I highlighted the steps taken, as well as errors and troubleshooting steps done to resolve the errors.

**Comment by joyisi** [comment]
# Migrating Birmingham Db Instance

These are the steps taken to resolve the above issues.

1. Clean the new db instance(birmingham-city-prod)
    - Exec into the ckan pod
    - Log in as postgress admin
    - Drop db Birmingham-city db and datastore respectively by running these commands
    ```
    select pg_terminate_backend(pid) from pg_stat_activity where datname='birmingham-city-prod';
   drop database "birmingham-city-prod";
    select pg_terminate_backend(pid) from pg_stat_activity where datname='birmingham-city-prod-datastore';
    drop database "birmingham-city-prod-datastore";
    ```
2. Take psql dump of old instance
    - Get latest backup from backup bucket
    - Refactor it for new user(birmingham-city)
    - Upload to old instance pod (birmingham-pod)
    ```
    kubectl cp -n dx-helm-birmingham-prod /FILENAMEWITHPATH birmingham-prod-ckan-6cdc4d4bf5-48qw7:/tmp
    kubectl exec -it -n dx-helm-birmingham-prod birmingham-prod-ckan-6cdc4d4bf5-48qw7 -- bash
    ```
 3. Create db for new instance
     - Log in as postgres admin user
     - Create db for new ckan instance and datastore using these commands
    ```
    CREATE DATABASE  "birmingham-city-prod";
    CREATE DATABASE "birmingham-city-prod-datastore";
    ```
    - Grant necessary permissions
    ```
    GRANT "birmingham-city-prod" to "postgres";
    GRANT "birmingham-city-prod-datastore" to "postgres";
    GRANT "birmingham-city-prod-datastore-ro" to "postgres";
    --- endblock

    REVOKE CREATE ON SCHEMA public FROM PUBLIC;
    REVOKE USAGE ON SCHEMA public FROM PUBLIC;
    GRANT CREATE ON SCHEMA public TO "birmingham-city-prod";
    GRANT USAGE ON SCHEMA public TO "birmingham-city-prod";
    GRANT CREATE ON SCHEMA public TO "birmingham-city-prod-datastore";
    GRANT USAGE ON SCHEMA public TO "birmingham-city-prod-datastore";
    ALTER DATABASE "birmingham-city-prod" OWNER TO "birmingham-city-prod";
    ALTER DATABASE "birmingham-city-prod-datastore" OWNER TO "birmingham-city-prod";
    REVOKE CONNECT ON DATABASE "birmingham-city-prod" FROM "birmingham-city-prod-datastore-ro";
    GRANT CONNECT ON DATABASE "birmingham-city-prod-datastore" TO "birmingham-city-prod-datastore-ro";
    GRANT USAGE ON SCHEMA public TO "birmingham-city-prod-datastore-ro";
    ALTER DATABASE "birmingham-city-prod" OWNER TO "birmingham-city-prod";
    ```
4. Restore ckan db backup to new instance
    - Log in as postgres user
    - Restore dump from old instance
    ```
    bash-4.4# pg_restore postgres://postgres:F6aEvUIhRUnWR1HzOv8iKYIMvJil0vRiTrIkYMn5EgmvQC39ls@10.54.0.12:5432/birmingham-city-prod < database-backups_birmingham-prod_29-08-22_birmingham-prod290822122659.sql
    ```
5. Upgrade DB Schema since we are importing from an old version
    - Exec into ckan pod(birmingham-city-prod)
    - Perfom db upgrade
    ```
    /srv/app # ckan -c ckan.ini db upgrade
    ```
6. Re-index solr
    ```
    /srv/app # ckan -c ckan.ini search-index rebuild
    ```
    
## Errors Encountered + Troubleshooting Steps
### error 1
```
tar: unrecognized option: –
BusyBox v1.27.2 (2017-12-12 10:41:50 GMT) multi-call binary.
```
### troubleshooting steps
1. Extension was changed to ".txt", refactored to new user (birmingham-city) and saved as ".sql"
2. New file was uploaded to old instance pod
    ```
    kubectl cp -n dx-helm-birmingham-prod /Users/jojo/Downloads/database-backups_birmingham-prod_29-08-22_birmingham-prod290822122659.sql birmingham-prod-ckan-6cdc4d4bf5-48qw7:/tmp
    ```

### error 2
```
pg_restore: [archiver] could not open input file "postgres://postgres:F6aEvUIhRUnWR1HzOv8iKYIMvJil0vRiTrIkYMn5EgmvQC39ls@10.54.0.12:5432/birmingham-city-prod": No such file or directory

```

### troubleshooting steps
1. New pg_dump of old instance was created and uploaded to gcp bucket
2. File was downloaded and restored on new instance


### error 3
```
(psycopg2.errors.UndefinedColumn) column resource.metadata_modified does not exist
LINE 1: ...e.size, resource.created, resource.last_modified, resource.m...

```

### troubleshooting steps
1. Performed db upgrade
    ```
    ckan -c ckan.ini db upgrade
    ```

**Comment by joyisi** [comment]
# Migrating Birmingham Db Instance

These are the steps taken to resolve the above issues.

1. Clean the new db instance(birmingham-city-prod)
    - Exec into the ckan pod
    - Log in as postgress admin
    - Drop db Birmingham-city db and datastore respectively
    
2. Take psql dump of old instance
    - Get latest backup from backup bucket
    - Refactor it for new user(birmingham-city)
    - Upload to old instance pod (birmingham-pod)
    
 3. Create db for new instance
     - Log in as postgres admin user
     - Create db for new ckan instance and datastore 
    - Grant necessary permissions
   
4. Restore ckan db backup to new instance
    - Restore dump from old instance
   
5. Upgrade DB Schema since we are importing from an old version
    - Exec into ckan pod
    - Perfom db upgrade
   
6. Re-index solr

**Comment by juanbrits** [comment]
@anuveyatsu is there anything required to progress on this ticket?

**Comment by joyisi** [comment]
@anuveyatsu Datastore migration is completed, and has been tested. The pending migration at the moment is filestore migration. Do i go ahead with that?

**Comment by juanbrits** [comment]
Hi @joyisi have you received feedback on this issue?

**Comment by juanbrits** [comment]
> @anuveyatsu Datastore migration is completed, and has been tested. The pending migration at the moment is filestore migration. Do i go ahead with that?

Hi @joyisi have you received feedback on this?
