### ISSUE TITLE
Dataset Visualization on Homepage

### ISSUE THREAD

**Issue by juanbrits** [datopian/birmingham-city-observatory#20]
The client would like to see dataset visualizations on the homepage. 

### Acceptance criteria

- [ ] I can view Housing, Census and Ukraine Dataset visualization on the homepage

### Tasks

- [x] Implement housing visuals as per client's email
- [x] Make Adjustments to the housing visuals as per client's request
- [x] Implement Deprivation graph as per client's request

**Comment by juanbrits** [comment]
@juanbrits follow up on visualizations from client

**Comment by juanbrits** [comment]
@lucasmbispo see email sent from client re housing data visuals:

![image](https://user-images.githubusercontent.com/103997912/191454743-38393ba7-38a6-44be-aed7-c12efac4f821.png)

**Comment by lucasmbispo** [comment]
Updated as advised per client.
Ukraine dataset still lacking by the client.
Census dataset to be repaired by Datopian team.

**Comment by juanbrits** [comment]
@lucasmbispo what is the blocker on the Census dataset?

**Comment by juanbrits** [comment]
Also please look at the deprivation dataset. This also needs to be visualized.

**Comment by lucasmbispo** [comment]
@juanbrits The blocker is the issue with the portal's Datastore/Datapusher which is already being worked by @joyisi and the Hosting & Support group.

**Comment by ZoeWright** [comment]
For Housing, I have now uploaded the Right To Buy data as an extra resource under the 'Birmingham City Council Housing Data' page, to help with the Right To Buy Housing visual.

**Comment by ZoeWright** [comment]
Also, to clarify how to show the Deprivation data: please use the 'IMD 2019 by Birmingham Ward' data resource under the 'Indices of Deprivation (IMD) 2019' page. Please could it be implemented as a bar graph displaying the column data 'Index of Multiple Deprivation (IMD) 2019 Ward Decile (where 1 is 10% Most Deprived Nationally)', but ordered by the column 'Index of Multiple Deprivation (IMD) 2019 Birmingham Ward Rank' from highest to lowest value (although this column will not be displayed, only used to order the data).  Any questions or queries, let me know.

If there are any issues, let me know.

**Comment by juanbrits** [comment]
Hello @ZoeWright - we've implemented the visualizations as requested. Please see below: 

![image](https://user-images.githubusercontent.com/103997912/194814506-7aaffbc7-dc26-4587-bc30-ea34d70ce534.png)

![image](https://user-images.githubusercontent.com/103997912/194814540-a04d1d45-fbe7-4a71-9a5c-e111f044820a.png)

![image](https://user-images.githubusercontent.com/103997912/194814581-5803b1c7-7b5d-4b13-9074-42fb7ded6b4a.png)

We trust all is in order?

**Comment by juanbrits** [comment]
@lucasmbispo as discuissed in today's meeting, please find the data for the last housing data chart here:

Housing Data Visualization: Properties Sold under Right to Buy Scheme  https://birmingham-city-observatory.vercel.app/@birmingham-city-council/birmingham-city-council-housing-data/r/Properties%20Sold%20under%20Right%20to%20Buy%20Scheme
