### ISSUE TITLE
Implement Datasets Page

### ISSUE THREAD

**Issue by juanbrits** [datopian/birmingham-city-observatory#21]
### Job Story

As a user on the Datasets Page I should be able to search for datasets and filter by organizations & groups. 
I should be able to refine my search results further by organization, groups and keywords.

### Tasks

- [x] Review resource page alignment (comment below)
- [x] Review Resource page sidebar (comment below)
- [x] Implement text to be received from client
- [x] Investigate Preview Data

**Comment by juanbrits** [comment]
@lucasmbispo to investigate what is still required on this page

**Comment by juanbrits** [comment]
Resource page text alignment

![image](https://user-images.githubusercontent.com/103997912/191213826-db232140-7af3-4a88-864c-e3f15005561d.png)

**Comment by juanbrits** [comment]
Resource page sidebar:

![image](https://user-images.githubusercontent.com/103997912/191214072-11afad9b-5c93-46ab-9f3d-a451e80178c9.png)

**Comment by juanbrits** [comment]
@lucasmbispo please look into the Data Preview as well on a resource. It seems this is not working.

**Comment by demenech** [comment]
@juanbrits @lucasmbispo there's another issue for the resources. @joyisi is taking a look at it.

**Comment by demenech** [comment]
@juanbrits `Implement text to be received from client` - Not sure about this one

**Comment by demenech** [comment]
PR: https://github.com/datopian/portal-birmingham-city-observatory/pull/23
- + some minor fixes, you can check the commit messages

**Comment by juanbrits** [comment]
@demenech  what is happening with preview data? Still doesnt seem to work?

**Comment by demenech** [comment]
@juanbrits yes

**Comment by juanbrits** [comment]
@demenech I have noted that there are still plenty of datasets where the resource preview. Please look into this and get resolved asap.

**Comment by juanbrits** [comment]
@joyisi please can you assist here? We believe you implemented a solution for us however it does not seem to have been applied across all the datasets. 

There are datasets we are unable to preview the resources:

![image](https://user-images.githubusercontent.com/103997912/194537532-92b5a3d5-1c8a-4a4b-8470-9962ff47e416.png)







![image](https://user-images.githubusercontent.com/103997912/194537435-2a831dda-2c11-4cef-935b-6c93f876af61.png)

I would like to know if this is going to be an issue for all datasets? If it is should we not look at implementing a solution?

**Comment by demenech** [comment]
@juanbrits I'm sorry, earlier this morning I had forgot about this:
Joy provided us the info that the resource names have a maximum amount of characters and that's what's breaking the previews.

**Comment by juanbrits** [comment]
Issue has been resolved - previews are available where column text lengths do not exceed 64 chars.
