### ISSUE TITLE
Implement News Page

### ISSUE THREAD

**Issue by juanbrits** [datopian/birmingham-city-observatory#24]
### Job Story

As a user I would like to see Birmingham City Observatory's news on the data portal. 

### Tasks

- [x] Use Birmingham City Council Twitter on News Page
- [x] enable articles plugin for Birmingham
- [x] Ensure auto-scroll is working for tweets
- [x] Currently RTs it's not clear what's a RT. Find a solution for that.
- [x] Implement text to be received from client 
- [x] Add arrows to last tweets

**Comment by juanbrits** [comment]
@demenech  updated comment as per our meeting today

**Comment by demenech** [comment]
PR: https://github.com/datopian/portal-birmingham-city-observatory/pull/25
Preview: https://birmingham-city-observatory-pzxk8imli-datopian1.vercel.app/blog

CC: @juanbrits

**Comment by juanbrits** [comment]
@demenech I see we have test articles in the preview - what needs to happen in order for the twitter articles to appear?

**Comment by demenech** [comment]
@juanbrits oooh, the tweets were added as a section in the news page. I may have misunderstood this requirement.

**Comment by demenech** [comment]
@juanbrits about the RTs - For now I have just disabled RTs, so it's going to display only original tweets. I did this because the complexity for indicating RTs is considerably higher, but if needed I sure can implement that.

**Comment by juanbrits** [comment]
@lucasmbispo please can you have a look at the spelling error on news page with the client text:
"new" should be "news"
![image](https://user-images.githubusercontent.com/103997912/194289072-72dd4790-af29-4d8f-a6c4-b9c709a8039b.png)

**Comment by demenech** [comment]
@juanbrits I'm just confirming this has been fixed.

**Comment by juanbrits** [comment]
Closing issue as page has been implemented.
