### ISSUE TITLE
Home Page Implementation

### ISSUE THREAD

**Issue by juanbrits** [datopian/birmingham-city-observatory#28]
### Acceptance Criteria

As a user I can navigate to all tabs, carousels, datasets etc, I can see data visualizations, I can see the most recent data. 

### Tasks

- [x] Implement dataset visualizations for housing data: https://birmingham-city-observatory.vercel.app/search?fq=groups:(housing) 
- [x] Birmingham to supply more data and example visualizations on Census and Ukraine Data visualizations
- [x] Population pyramid for age data
- [x] Implement Text For Home Page to be supplied by client
- [x] #17 
- [x] #20 
- [x] #10 
- [x] On home screen replace Open Data with Be Curious. 
- [x] Be Curious should be clickable and folds open to display home text sent by client
- [x] Client requested that we remove "Open Data" from underneath Birmingham on the Home Page heading
- [x] Client requested that Latest News and Featured Datasets be moved to the top of the page above Interesting Insights
- [x] Upload home page text as per Jagdeep’s email
- [x] Searchbar Placeholder = Search For Data
- [x] Add a Theme Carousel heading = Browse Data By Theme
- [ ] Standardise theme icon colours on the home page

**Comment by juanbrits** [comment]
https://birmingham-city-observatory.vercel.app/search?fq=groups:(housing) 
https://birmingham-city-observatory.vercel.app/search?fq=groups:(demographics)

**Comment by juanbrits** [comment]
@lucasmbispo I've added new tasks - please review.

**Comment by juanbrits** [comment]
@lucasmbispo updated task for you on the Home Page. Please review and advise if all is clear?

**Comment by lucasmbispo** [comment]
Everything is clear according to the last PR.

**Comment by juanbrits** [comment]
@lucasmbispo please can we make some changes?

The heading highlighted below should be centered with the carousel themes:

![image](https://user-images.githubusercontent.com/103997912/195524976-489ba4ad-d163-4f24-968f-b9abd619f503.png)

The placeholder in the searchbar should read as: Search for data, not Search your data:

![image](https://user-images.githubusercontent.com/103997912/195525102-5963470f-636e-4922-a45a-4f3d5e7c94a4.png)

**Comment by juanbrits** [comment]
@lucasmbispo some more changes please:

The home page text under Birmingham should be as per the below:

"Birmingham is the second largest city in the UK with a population of over 1,144,900 people. It is also one of the youngest UK cities with just over 40% of our residents being under 30 years of age (census 2021). 

The city is divided into 10 parliamentary constituencies and 69 wards that cover approximately 103 square miles with a population density of 42.75 persons per hectare of land. This is equivalent to around 31 people living on each football pitched size area of land. 

With a city of this size, open data is integral to enable maximisation of opportunities for growth, support economic development, tackle inequalities and level up Birmingham. 

The Birmingham City Observatory brings together a wide range of information to enable openness and transparency of data, and to gain a richer understanding of the city.

This exciting platform provides insights and evidence into key datasets to create a widely understood ‘single version of the truth’ about the city. It allows you to visualise performance on key datasets, and were made available, to drill down within our 69 wards and/or to lower layer super output area level (LSOA).

The platform also allows you to download data to use as you see fit, for those curious minds wanting to gain a deeper understanding and explore datasets.

Our datasets have been categorised into key themes below. As we develop the platform over time, these themes will have more datasets available. This will support our long-term evidence-based approach to inform decision making and support improvement."

Please implement the text box in a similar fashion to the "Join The Curious Ones" text as below:

![image](https://user-images.githubusercontent.com/103997912/195526583-d9d3c1f5-28f2-4bb3-88b7-3138751f9809.png)

**Comment by juanbrits** [comment]
And also please standardise the theme icon colours on the home page:

As per your suggestion the icon colours would match the visualisation:

**On Data Visuals:**
Census 2021 is incorrect as they are all blue. This should be fixed:
![image](https://user-images.githubusercontent.com/103997912/195527302-5028a9ba-27b3-4ca5-940b-90faf32b75cd.png)

Deprivation is correct:

![image](https://user-images.githubusercontent.com/103997912/195527554-0c03089f-6bb6-4121-80be-eb0ff8ef3571.png)

BIRMINGHAM CITY COUNCIL HOUSING STOCK is incorrect as they are all blue. This should be fixed:

Featured datasets can remain blue:

![image](https://user-images.githubusercontent.com/103997912/195527881-dc3ec103-b534-44a9-828c-d45de7a953b3.png)

**Comment by juanbrits** [comment]
@lucasmbispo has this chart been linked up with actual data yet?
![image](https://user-images.githubusercontent.com/103997912/195533306-e22f84be-13ba-4e62-9be7-e8c7d1280284.png)
