### ISSUE TITLE
Homepage UI improvements

### ISSUE THREAD

**Issue by demenech** [datopian/birmingham-city-observatory#29]
## Tasks:
- [x] Footer should not touch the sides of the screen:
![ss-2022-09-21-17:00:48](https://user-images.githubusercontent.com/16550934/191599365-32d82b42-6923-4981-9a50-86668dfcd217.png)
- [x] Navbar should not touch the sides of the screen:
![ss-2022-09-21-17:01:23](https://user-images.githubusercontent.com/16550934/191599461-30333e94-9817-4857-a4d3-05dd9e46ee07.png)
- [x] Home page Datasets cards 
    - [x]  Cards are not using the right font style:
    - [x] Images are not being displayed with the correct aspect ratio
    - [x] Descriptions are not dynamic
    - [ ] 
![ss-2022-09-21-17:02:09](https://user-images.githubusercontent.com/16550934/191599578-02e57f04-3ffc-452d-835f-0e51625b96ba.png)

**Comment by demenech** [comment]
@juanbrits some small issues I noticed

PR: https://github.com/datopian/portal-birmingham-city-observatory/pull/27
