### ISSUE TITLE
SEO

### ISSUE THREAD

**Issue by demenech** [datopian/birmingham-city-observatory#33]
# Tasks
- [x] Create a sitemap.xml
- [x] Make sure sitemap.xml is available as a resource in the website
- [x] Create robots.txt
- [x] Make sure robots.txt contain the sitemap
- [x] Investigate about robots.txt domain migration
- [x] Investigate SEO tools to check what improvements could be done in terms of SEO
- [x] Improve the score for the website on Google Lighthouse

**Comment by demenech** [comment]
I used this dependency: https://www.npmjs.com/package/next-sitemap
What I did was creating a config for this that makes it automatically generate sitemap.xml and robots.txt
it also generates a sitemap for the dynamic resources (organizations, datasets, resources and news).

**Comment by demenech** [comment]
![ss-2022-10-11-17:03:23](https://user-images.githubusercontent.com/16550934/195187688-45aa6ea9-1e1d-4b3c-8fab-39747124e6b4.png)
I believe the SEO score is currently good enough. The only missing recommendation would be having descriptive texts for the links, but as the links are dybamic, I think it's not worth working on it. @juanbrits

**Comment by juanbrits** [comment]
That is great, Demenech. Thank you.
May I ask, is it possible to translate your page to inglės please and take
a snip?

**Comment by demenech** [comment]
![image](https://user-images.githubusercontent.com/16550934/195303074-7deb43fd-c826-410d-a811-997659508650.png)

@juanbrits
