### ISSUE TITLE
Custom domain setup

### ISSUE THREAD

**Issue by anuveyatsu** [datopian/birmingham-city-observatory#4]
## Acceptance criteria

- [x] I can access the frontend site using birmingham.cityobservatory.gov.uk domain
- [ ] I can access the admin site using admin.birmingham.cityobservatory.gov.uk domain

## Tasks

- [x] Issue a new domain for frontend - birmingham.cityobservatory.gov.uk
- [ ] Issue a new domain for admin site - admin.birmingham.cityobservatory.gov.uk

## Analysis

Instructions for frontend domain:

Instructions for admin domain:

**Comment by juanbrits** [comment]
I can access the frontend using: https://www.cityobservatory.birmingham.gov.uk
