### ISSUE TITLE
Fix search page filters

### ISSUE THREAD

**Issue by anuveyatsu** [datopian/birmingham-city-observatory#48]
Currently keywords (aka tags) are displayed incorrectly, e.g., it should look similar to organizations and themes filter. We are also missing filters such as licenses and formats.

Currently: https://www.cityobservatory.birmingham.gov.uk/search

Example of working: https://data.ssen.co.uk/search

## Acceptance criteria

- [ ] Tags filter looks similar to organizations and themese filters.
- [ ] I can filter by tags (keywords) or multiple tags.
- [ ] I can filter by formats.
- [ ] I can filter by licenses.

## Tasks

- [ ] Fix the look of tags filter.
- [ ] Add/implement formats filter.
- [ ] Add/implement licenses filter.

**Comment by RonaldojCampos** [comment]
craeted pull request 
https://github.com/datopian/portal-birmingham-city-observatory/pull/76

**Comment by RonaldojCampos** [comment]
merged
