### ISSUE TITLE
Dataset page issues

### ISSUE THREAD

**Issue by anuveyatsu** [datopian/birmingham-city-observatory#49]
See example here: https://www.cityobservatory.birmingham.gov.uk/@birmingham-city-observatory/ward-profiles-april-2023

## Tasks

- [ ] Size information should be human readable. Currently it shows bytes which is difficult to read.
- [ ] Tags should be clickable and redirect to search page with results showing datasets related to the tag clicked.
- [ ] Formats should be clickable same as tags.
- [ ] Add pagination for resources list so that we show only 10 per page.

**Comment by RonaldojCampos** [comment]
created pull request
https://github.com/datopian/portal-birmingham-city-observatory/pull/75

**Comment by RonaldojCampos** [comment]
merged
