### ISSUE TITLE
Prepare and load metadata and data into the new instance

### ISSUE THREAD

**Issue by anuveyatsu** [datopian/birmingham-city-observatory#5]
## Tasks

- [x] Review list of organizations and make amendments when required
- [x] Review list of groups and make amendments when required
- [x] Publish new datasets

**Comment by juanbrits** [comment]
Client has uploaded datasets and we are able to preview and download datasets
