### ISSUE TITLE
Light branding according to the main website of the city (colours/fonts).

### ISSUE THREAD

**Issue by anuveyatsu** [datopian/birmingham-city-observatory#9]
## Acceptance

- [x] The site looks aligned with the general City's branding - https://birmingham-city-observatory.vercel.app/

## Tasks

- [x] Update headlines, titles, descriptions, meta tags etc.
- [x] Update colours.
- [x] Update fonts.
- [x] Remove the Twitter component from the home page (we agreed there will be no Twitter feed for now).
- [x] Remove visualizations for now.
- [x] (Need to confirm) Replace pictures in the hero element with a background colour (E.g., pick one from the colour pallette of the city).
